- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ../creds/big_ipcreds.yaml

  vars:
    uri_method: POST

  tasks:
    - name: Create a service using AS3
      uri:
        url: https://10.1.1.130/mgmt/shared/appsvcs/declare
        method: "{{ uri_method }}"
        user: "{{ user_creds }}"
        password: "{{ user_pass }}"
        body: "{{ lookup('file','as3_dec.json') }}"
        force_basic_auth: yes
        status_code: 200
        validate_certs: no
        body_format: json